version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: brain_agriculture
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  brain_agriculture:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env 
    depends_on:
      - postgres
    command: ["npm", "run", "start:prod"]

volumes:
  postgres_data:
